# variáveis
@base_url = http://127.0.0.1:5000
### create payment
POST {{base_url}}/payments/pix
Content-Type: application/json

{
  "value": 500
}

HTTP/1.1 200  - OK
server: Werkzeug/3.0.2 Python/3.11.5
date: Wed, 24 Apr 2024 07:21:01 GMT
content-type: application/json
content-length: 225
connection: close