# variáveis
@base_url = http://127.0.0.1:5000
###
POST {{base_url}}/payments/pix
Content-Type: application/json

{
  "value": 500
}

HTTP/1.1 500  - INTERNAL SERVER ERROR
server: Werkzeug/3.0.2 Python/3.11.5
date: Wed, 24 Apr 2024 18:11:47 GMT
content-type: text/html; charset=utf-8
content-length: 20203
connection: close